const { chromium } = require('playwright');
const U='file://' + require('path').resolve(__dirname,'../app/standalone.html') + '';
let pass=0,fail=0; const errs=[];
const ok=(c,m)=>{c?(pass++,console.log('  ✓ '+m)):(fail++,console.log('  ✗ '+m));};
async function login(p,c,w){await p.goto(U);await p.waitForSelector('#loginCode');
 await p.fill('#loginCode',c);await p.fill('#loginPass',w);
 await p.click('form[data-form="login"] button[type="submit"]');
 await p.waitForSelector('.sidebar__nav');await p.waitForFunction(()=>!document.querySelector('.page-loader'));
 await p.waitForTimeout(500);}
const go=async(p,r)=>{await p.click('.sidebar__nav [data-route="'+r+'"]');await p.waitForTimeout(500);};
// v2.2: подтвердить экран параметров заказа (получатель/дата/заморозка) — открыть прайс-лист
const confirmSetup=async(p)=>{await p.click('[data-action="confirm-setup"]');await p.waitForTimeout(700);};
(async()=>{
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1680,height:1000}});
p.on('pageerror',e=>errs.push('JS: '+e.message));
p.on('console',m=>{if(m.type()==='error'&&!/403/.test(m.text()))errs.push('console: '+m.text());});

console.log('\n[ ЗАГРУЗКА ПО API КИС ]');
await login(p,'B-1024','master1024');
ok(await p.locator('.sidebar__nav').isVisible(),'Вход выполнен');
const hero=await p.locator('.hero-card').textContent();
ok(hero.includes('Перекрёсток'),'Покупатель из /payers');
const kpi=await p.locator('.grid').first().textContent();
ok(kpi.includes('Сальдо'),'Сальдо из SumOutSaldoCalc');

console.log('\n[ ЭКРАН ПАРАМЕТРОВ ЗАКАЗА ]');
await go(p,'order');
ok(await p.locator('.setup-card').isVisible(),'Экран параметров показан вместо прайс-листа');
ok((await p.locator('.product').count())===0,'Прайс-лист скрыт до подтверждения параметров');
ok(await p.locator('#setupOutletSel').isVisible(),'Получатель выбирается — покупатель с несколькими точками');
ok((await p.locator('#setupDateSel option').count())>0,'Список дат на экране параметров заполнен');
ok((await p.locator('#setupFreezeChk').count())===1,'Чекбокс «Заморозка» на экране параметров');
await confirmSetup(p);

console.log('\n[ ОФОРМЛЕНИЕ: КАТАЛОГ ]');
ok(await p.locator('.order-params').isVisible(),'Панель параметров заказа видна');
const groupTxt=await p.locator('.order-params__item--static').first().textContent();
ok(/Хлебобулочные/.test(groupTxt),'Группа показана как факт, без переключателя: '+groupTxt.trim());
ok((await p.locator('.order-params select').count())===0,'На каталоге группа/дата не редактируются (нет select)');
ok((await p.locator('.order-params__note').count())===0,'Строка «Получатель принимает…» убрана');
ok((await p.locator('.seg--type .seg__btn').count())===3,'Тип — 3 варианта (Вся/В заказе/Акция), без «Обычная»');
const hbiCount=await p.locator('.product').count();
ok(hbiCount>0,'Матрица ХБИ загружена ('+hbiCount+' позиций)');
ok((await p.locator('.price-disc').count())>0,'Показан процент скидки ProcSkd');
const promoN=await p.locator('.product--promo').count();
ok(promoN>0&&promoN<hbiCount,'Акция ≠ скидка по договору ('+promoN+' из '+hbiCount+')');

console.log('\n[ КАТЕГОРИИ — ЧИПСЫ ]');
const chipCount=await p.locator('.cat-chip').count();
ok(chipCount>=5,'Чипсы категорий отрисованы ('+chipCount+')');
const allActiveByDefault=await p.locator('.cat-chip.is-active').count();
ok(allActiveByDefault===chipCount,'По умолчанию отмечены все категории');
ok((await p.locator('.cat-chip--all.is-active').count())===1,'Чип «Все» подсвечен, пока ничего не снято');
const catChipsOnly = p.locator('.cat-chip:not(.cat-chip--all)');
const firstChipName=await catChipsOnly.nth(0).locator('span').first().textContent();
await catChipsOnly.nth(0).click();
await p.waitForTimeout(400);
const afterUncheck=await p.locator('.product').count();
ok(afterUncheck<hbiCount,'Снятие категории «'+firstChipName.trim()+'» сужает список ('+afterUncheck+' из '+hbiCount+')');
ok((await p.locator('.cat-chip--all.is-active').count())===0,'Чип «Все» перестал быть активным после снятия одной категории');
await p.click('.cat-chip--all');
await p.waitForTimeout(400);
ok((await p.locator('.product').count())===hbiCount,'Чип «Все» возвращает полный список');

console.log('\n[ ФИЛЬТР ПО ТИПУ ]');
await p.click('.seg--type [data-type="in-cart"]');
await p.waitForTimeout(400);
ok((await p.locator('.product').count())===0,'«В заказе» пусто — корзина ещё не заполнена');
await p.click('.seg--type [data-type="promo"]');
await p.waitForTimeout(400);
ok((await p.locator('.product').count())===promoN,'«Акция» показывает ровно акционные позиции ('+promoN+')');
await p.click('.seg--type [data-type="all"]');
await p.waitForTimeout(400);
ok((await p.locator('.product').count())===hbiCount,'«Вся» возвращает полный список');

console.log('\n[ СМЕНА ГРУППЫ ЧЕРЕЗ ЭКРАН ПАРАМЕТРОВ ]');
await go(p,'dashboard');
await go(p,'order');
ok(await p.locator('.setup-card').isVisible(),'Повторный вход на вкладку — снова экран параметров');
await p.click('.setup-toggle');
await p.waitForTimeout(200);
await confirmSetup(p);
const zpfCount=await p.locator('.product').count();
ok(zpfCount>0&&zpfCount!==hbiCount,'Группа ЗПФ (заморозка) даёт другую матрицу ('+zpfCount+' позиций)');
const hasFrostChip=await p.locator('.cat-chip', {hasText:'Заморозка'}).count();
ok(hasFrostChip>0,'В группе ЗПФ среди чипсов есть «Заморозка»');

console.log('\n[ ОТПРАВКА ЗАКАЗА ]');
await go(p,'dashboard');
await go(p,'order');
await confirmSetup(p);
await p.locator('.product [data-lots-input]').first().fill('40');
await p.locator('.product [data-lots-input]').first().dispatchEvent('input');
await p.waitForTimeout(400);
ok(!(await p.locator('#sumSubmit').isDisabled()),'Кнопка проверки активна');
await p.click('#sumSubmit');
ok(await p.locator('.review-panel').isVisible(),'Перед отправкой открыта проверка заказа');
ok((await p.locator('.review-item').count())===1,'В проверке только выбранная позиция');
await p.click('#reviewSubmit');
await p.waitForTimeout(900);
const toast=await p.locator('.toast').count()?await p.locator('.toast').textContent():'';
ok(/принят на/i.test(toast),'Заказ создан через POST /orders: '+toast.slice(0,60));
ok(await p.locator('.orders-history__table').isVisible(),'Открыта История');

console.log('\n[ ИСТОРИЯ: ПОМЕТКА ПРО 14 ДНЕЙ ]');
const scopeNote=await p.locator('.orders-history__scope-note').textContent();
ok(/14 дн/.test(scopeNote),'Есть аккуратная пометка про 14-дневное окно: '+scopeNote.trim());

await p.waitForFunction(()=>!document.querySelector('.toast'),{timeout:8000}).catch(()=>{});
console.log('\n[ КАРТОЧКА ЗАКАЗА ]');
const accIdx=await p.$$eval('.orders-history__table tbody tr',rs=>rs.findIndex(r=>/Принят/.test(r.textContent)));
await p.locator('.orders-history__table tbody tr').nth(accIdx).click();
await p.waitForTimeout(900);
ok(await p.locator('.modal').isVisible(),'Модалка открыта');
const mtxt=await p.locator('.modal').textContent();
ok(/Хлебобулочные|Замороженные/.test(mtxt),'Показана группа заказа');
ok((await p.locator('.modal .table tbody tr').count())>0,'Позиции догружены из /order-details');
ok(/Принят|Маршрутизирован|В пути|Отгружен/.test(mtxt),'Статус из КИС по-русски');

console.log('\n[ ЛОТКИ/ШТУКИ И КОРРЕКТИРОВКА В МОДАЛКЕ ]');
const dualRows=await p.locator('.modal .qty--lotonly[data-order-item]').count();
ok(dualRows>0,'В модалке позиции показаны Лотками/Штуками, как в оформлении заказа ('+dualRows+')');
ok(await p.locator('.btn--primary[data-action="repeat-order"]').isVisible(),'До правок — кнопка «Повторить заказ»');
const oiRow=p.locator('.modal .qty--lotonly[data-order-item]').first();
await oiRow.locator('[data-oi-pcs-input]').click();
ok(await p.locator('.modal').isVisible(),'Клик по полю не закрывает карточку');
await p.locator('.modal__body').click({position:{x:5,y:5}});
ok(await p.locator('.modal').isVisible(),'Клик по свободной области карточки не закрывает её');
await oiRow.locator('[data-oi-step="pcs"][data-dir="+"]').click();
await p.waitForTimeout(300);
ok(await p.locator('.btn--primary[data-action="save-order-edits"]').isVisible(),'После правки кнопка стала «Корректировка заказа»');
await p.click('[data-action="save-order-edits"]');
await p.waitForSelector('.toast',{timeout:5000}).catch(()=>{});
const corrToast=await p.locator('.toast').count()?await p.locator('.toast').textContent():'';
ok(/изменён/i.test(corrToast),'PATCH корректировки выполнен: '+corrToast.slice(0,60));
await p.waitForTimeout(400);
ok(!(await p.locator('.modal').isVisible()),'Модалка закрылась после сохранения корректировки');

await p.waitForFunction(()=>!document.querySelector('.toast'),{timeout:8000}).catch(()=>{});
console.log('\n[ ПОВТОР ЗАКАЗА ИЗ ИСТОРИИ ]');
await p.locator('.orders-history__table tbody tr').nth(accIdx).click();
await p.waitForTimeout(700);
ok(await p.locator('.modal').isVisible(),'Модалка снова открыта, чтобы повторить заказ');
await p.click('[data-action="repeat-order"]');
await p.waitForTimeout(700);
ok((await p.locator('.sidebar__nav [data-route="order"].active').count())===1,'Повтор переключил на вкладку «Оформить заказ»');
ok(await p.locator('.setup-card').isVisible(),'Повтор из истории возвращает на экран параметров, а не сразу в прайс-лист');
ok((await p.locator('.product').count())===0,'Прайс-лист при повторе из истории пока не открыт');
const setupOutletVal=await p.locator('#setupOutletSel').inputValue().catch(()=>null);
ok(!!setupOutletVal,'Получатель на экране параметров подставлен из повторяемого заказа');
await confirmSetup(p);
ok((await p.locator('.product').count())>0,'После подтверждения параметров прайс-лист открылся');
const sumUnitsTxt=await p.locator('#sumUnits').textContent();
ok(Number(sumUnitsTxt)>0,'Корзина после повтора из истории не пустая: '+sumUnitsTxt+' шт');

console.log('\n[ ПОВТОРИТЬ ПОСЛЕДНИЙ ЗАКАЗ С ЭКРАНА ПАРАМЕТРОВ ]');
await go(p,'dashboard');
await go(p,'order');
ok(await p.locator('.setup-card').isVisible(),'Новый заход на вкладку снова показывает экран параметров');
ok(await p.locator('[data-action="repeat-last"]').isVisible(),'Кнопка «Повторить последний заказ» видна');
await p.click('[data-action="repeat-last"]');
await p.waitForTimeout(900);
ok((await p.locator('.product').count())>0,'«Повторить последний заказ» сразу открывает прайс-лист');
const sumUnitsTxt2=await p.locator('#sumUnits').textContent();
ok(Number(sumUnitsTxt2)>0,'Корзина заполнена позициями последнего заказа: '+sumUnitsTxt2+' шт');

console.log('\n[ ФИЛЬТР ИСТОРИИ ]');
await go(p,'orders');
ok((await p.locator('#historyOutletSel').count())===1,'Фильтр по точке на месте');
const rowsAll=await p.locator('.orders-history__table tbody tr').count();
const oid=await p.evaluate(()=>document.querySelectorAll('#historyOutletSel option')[1].value);
await p.selectOption('#historyOutletSel',oid);await p.waitForTimeout(400);
ok((await p.locator('.orders-history__table tbody tr').count())<rowsAll,'Фильтр сужает список');

console.log('\n[ РОЛЬ ПОЛУЧАТЕЛЯ ]');
await p.close();
const p2=await b.newPage({viewport:{width:1400,height:900}});
p2.on('pageerror',e=>errs.push('JS: '+e.message));
await login(p2,'M-1467-01','magn2026');
ok((await p2.locator('.kpi').count())===3,'Получатель: 3 KPI без сальдо');
await go(p2,'order');
ok(await p2.locator('.setup-card').isVisible(),'Получатель: экран параметров показан');
ok((await p2.locator('#setupOutletSel').count())===0,'Получатель: шаг выбора получателя скрыт — точка одна и роль не покупатель');
ok(await p2.locator('.setup-step--static').isVisible(),'Получатель: точка показана статичной строкой');
await confirmSetup(p2);
ok(!(await p2.locator('.summary__ship').textContent()).includes('Сальдо'),'Получатель: сальдо скрыто в сводке');
ok(await p2.locator('.order-params').isVisible(),'Получатель: панель группы и даты видна');
ok((await p2.locator('.order-params select').count())===0,'Получатель: группа/дата тоже не редактируются на каталоге');
await p2.setViewportSize({width:390,height:844});
const mobileField=p2.locator('.product [data-lots-input]').last();
await mobileField.scrollIntoViewIfNeeded();
await mobileField.fill('10');
const mobileScroll=await p2.evaluate(()=>window.scrollY);
await p2.mouse.click(4,250);
ok(Math.abs(await p2.evaluate(()=>window.scrollY)-mobileScroll)<2,'Мобильный экран: клик по пустой области сохраняет прокрутку');
ok(await p2.locator('.mobile-review').isVisible(),'На телефоне закреплён итог заказа');
await p2.click('#mobileReviewButton');
ok(await p2.locator('.review-panel').isVisible(),'Мобильная панель открывает проверку');
await p2.locator('.review-panel__header [data-action="close-review"]').click();
ok(Math.abs(await p2.evaluate(()=>window.scrollY)-mobileScroll)<2,'Возврат из проверки сохраняет позицию длинного каталога');
await p2.close();

console.log('\n[ ОТМЕНА ЗАКАЗА (DELETE) ]');
const p4=await b.newPage({viewport:{width:1500,height:1000}});
p4.on('pageerror',e=>errs.push('JS: '+e.message));
await login(p4,'B-1024','master1024');
await go(p4,'order');
await confirmSetup(p4);
await p4.locator('.product [data-lots-input]').first().fill('50');
await p4.locator('.product [data-lots-input]').first().dispatchEvent('input');
await p4.waitForTimeout(400);
await p4.click('#sumSubmit');
await p4.click('#reviewSubmit');
await p4.waitForTimeout(900);
await p4.locator('.orders-history__table tbody tr').first().click();
await p4.waitForTimeout(800);
ok(await p4.locator('.modal').isVisible(),'Модалка нового заказа открыта');
ok((await p4.locator('[data-action="cancel-order"]').count())===1,'Кнопка «Отменить заказ» доступна для «Принят»');
await p4.click('[data-action="cancel-order"]');
await p4.waitForTimeout(400);
ok((await p4.locator('.confirm-modal').count())===1,'Спрошено подтверждение отмены');
await p4.click('[data-action="confirm-ok"]');
await p4.waitForSelector('.toast',{timeout:5000}).catch(()=>{});
const delToast=await p4.locator('.toast').count()?await p4.locator('.toast').textContent():'';
ok(/удал/i.test(delToast),'DELETE /api/v1/orders/{id} выполнен: '+delToast.slice(0,60));
const statusTxt=await p4.locator('.modal .pill').first().textContent().catch(()=>'');
ok(/Удал/i.test(statusTxt),'Статус в модалке — «Удалён»: '+statusTxt.trim());
await p4.close();

console.log('\n[ 402 — ЗАКАЗ ОТКЛОНЁН, НЕ ХВАТАЕТ СРЕДСТВ ]');
const p3=await b.newPage({viewport:{width:1500,height:1000}});
p3.on('pageerror',e=>errs.push('JS: '+e.message));
await login(p3,'B-1704','master1704');
await go(p3,'order');
const bannerTxt=await p3.locator('.banner--hold').textContent();
ok(/отклонён/.test(bannerTxt),'Баннер честно предупреждает об отклонении: '+bannerTxt.trim().slice(0,70));
await confirmSetup(p3);
await p3.locator('.product [data-lots-input]').first().fill('60');
await p3.locator('.product [data-lots-input]').first().dispatchEvent('input');
await p3.waitForTimeout(400);
await p3.click('#sumSubmit');
await p3.click('#reviewSubmit');
await p3.waitForSelector('.review-panel [role="alert"]',{timeout:5000});
const errToast=await p3.locator('.review-panel [role="alert"]').textContent();
ok(/не хватает средств/i.test(errToast),'402 показан в проверке заказа: '+errToast.slice(0,70));
ok((await p3.locator('.sidebar__nav [data-route="orders"].active').count())===0,'Заказ не создан — маршрут остался на «Оформить заказ»');
ok((await p3.locator('#sumUnits').textContent())!=='0','Корзина не сброшена после отказа — можно поправить и повторить');
await p3.close();

await b.close();
console.log('\n'+'='.repeat(50));
console.log('ПРОЙДЕНО: '+pass+'   ПРОВАЛЕНО: '+fail);
if(errs.length){console.log('\nОШИБКИ:');[...new Set(errs)].slice(0,8).forEach(e=>console.log('  ! '+e));}
else console.log('Ошибок JS нет.');
if(fail || errs.length) process.exitCode=1;
})().catch(err=>{console.error(err);process.exitCode=1;});
